services:
  - type: static
    name: cellular-ecosystem
    buildCommand: echo "Static site - no build needed"
    publishPath: .
    staticPublishPath: .
    envVars:
      - key: NODE_VERSION
        value: 18
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate 